//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.28 at 04:53:07 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.perscholas.com/xml/book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.glab31012.GLAB31012.xml.book;
